# Generated by Django 2.1.1 on 2018-09-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineCheckout',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.BigIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('checkout_request_id', models.CharField(default='', max_length=50)),
                ('account_reference', models.CharField(default='', max_length=50)),
                ('transaction_description', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_message', models.CharField(blank=True, max_length=100, null=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=50, null=True)),
                ('response_code', models.CharField(blank=True, max_length=5, null=True)),
                ('response_description', models.CharField(blank=True, max_length=100, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Online Checkout Requests',
                'db_table': 'tbl_online_checkout_requests',
            },
        ),
    ]
