# Generated by Django 2.1.1 on 2018-09-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_mpesa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinecheckout',
            name='mpesa_receipt_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='onlinecheckout',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
