# Generated by Django 2.1.1 on 2018-09-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_mpesa', '0002_auto_20180919_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineCheckoutResponse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('merchant_request_id', models.CharField(blank=True, max_length=50, null=True)),
                ('checkout_request_id', models.CharField(default='', max_length=50)),
                ('result_code', models.CharField(blank=True, max_length=5, null=True)),
                ('result_description', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Online Checkout Responses',
                'db_table': 'tbl_online_checkout_responses',
            },
        ),
        migrations.RemoveField(
            model_name='onlinecheckout',
            name='mpesa_receipt_number',
        ),
        migrations.RemoveField(
            model_name='onlinecheckout',
            name='received',
        ),
    ]
